services:
  const-max:
    image: graduss/ella-web-site:latest
    container_name: const-max
    restart: always
    env_file:
      - path: ../.env.const-max
        required: true
    networks:
      - live

  check-business:
    image: graduss/cb-web-app:latest
    container_name: check-business
    restart: always
    env_file:
      - path: ../.env.check-business
        required: true
    networks:
      - live

  nginx:
    image: nginx:latest
    container_name: ndinx-server
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - const-max
      - check-business
    restart: always
    networks:
      - live

networks:
    live:
      driver: bridge