services:
  const-max:
    image: graduss/ella-web-site:latest
    container_name: const-max
    restart: always
    env_file:
      - path: .env
        required: true
    networks:
      - live

  nginx:
    image: nginx:latest
    container_name: ndinx-server
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl/const-max.com:/etc/nginx/ssl/const-max.com:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - const-max
    restart: always
    networks:
      - live

networks:
    live:
      driver: bridge
